### ISSUE TITLE
为什么不用 esp32

### ISSUE THREAD

**Issue by dingyang666** [PairZhu/Paper-Lamp#1]
esp 便宜好用还大碗，集成度高代码还好写，甚至你还能用 wifi 然后在上面跑 http 前后端这样小程序都不用，建议用 esp32 重构

**Comment by PairZhu** [comment]
功耗太高，而且用http有点杀鸡用牛刀了

**Comment by PairZhu** [comment]
原计划就是用esp32，考虑到功耗才换成nano的

**Comment by dingyang666** [comment]
不高呀，在高也没 led 高，而且还有休眠，用 http 你可以买个酷炫的域名解析上去

**Comment by PairZhu** [comment]
我试过休眠，还是比nano不休眠的时候功耗高很多倍，原计划考虑用电池供电的，供电电路都焊接好了，想做成持久待机的，后来因为快递电池不给运才放弃的

**Comment by dingyang666** [comment]
另外能不能留个外壳的链接啥的

**Comment by PairZhu** [comment]
链接放进去了😂

**Comment by dingyang666** [comment]
感谢，我打算用 TINYPICO + 10000 mah 锂聚合物电池重构一个你感兴趣写前端吗

**Comment by dingyang666** [comment]
esp32 休眠电流 一般是 10uA

**Comment by PairZhu** [comment]
芯片理论上是的，但是开发板加了外围电路，不知道为啥，我用最深的休眠模式也10mA，重构又没啥难度，选择小程序而不是网页主要是为了实用性，小程序可以方便的放在手机屏幕上，pwa页面添加的时候不知道为什么，大多数人的手机都会遇到各种问题
